-- GasMan TMS - initial schema (PostgreSQL 16)
-- Conventions: integer identity PKs, snake_case, timestamptz everywhere, soft-archive via archived_at.

CREATE TABLE locations (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(30)  NOT NULL UNIQUE,
  name          varchar(150) NOT NULL,
  type          varchar(20)  NOT NULL CHECK (type IN ('PLANT','TERMINAL','DEPOT','DISTRIBUTOR','PARKING')),
  city          varchar(80),
  region        varchar(30)  NOT NULL,
  address       varchar(250),
  lat           double precision NOT NULL,
  lng           double precision NOT NULL,
  storage_capacity_mt numeric(10,1),
  contact_phone varchar(30),
  status        varchar(15)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_locations_type ON locations (type) WHERE status = 'ACTIVE';

CREATE TABLE distributors (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(30)  NOT NULL UNIQUE,
  name          varchar(150) NOT NULL,
  city          varchar(80)  NOT NULL,
  region        varchar(30)  NOT NULL,
  address       varchar(250),
  contact_name  varchar(120),
  phone         varchar(30),
  location_id   integer NOT NULL REFERENCES locations(id),
  status        varchar(15)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','ON_HOLD','INACTIVE')),
  credit_status varchar(15)  NOT NULL DEFAULT 'GOOD' CHECK (credit_status IN ('GOOD','WATCH','BLOCKED')),
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_distributors_region ON distributors (region, status);

CREATE TABLE routes (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(40) NOT NULL UNIQUE,
  origin_location_id      integer NOT NULL REFERENCES locations(id),
  destination_location_id integer NOT NULL REFERENCES locations(id),
  distance_km   numeric(8,1) NOT NULL,
  est_duration_min integer NOT NULL,
  path          jsonb NOT NULL,           -- [[lat,lng], ...] polyline (demo: synthetic)
  checkpoints   jsonb NOT NULL DEFAULT '[]', -- [{name, at: 0..1}]
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (origin_location_id, destination_location_id)
);

CREATE TABLE drivers (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   varchar(30)  NOT NULL UNIQUE,
  full_name     varchar(120) NOT NULL,
  phone         varchar(30),
  national_id_demo varchar(30),           -- clearly synthetic CNIC-like identifier
  license_no    varchar(40)  NOT NULL,
  license_class varchar(20)  NOT NULL DEFAULT 'HTV',
  status        varchar(15)  NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','ON_TRIP','OFF_DUTY','ON_LEAVE','SUSPENDED')),
  experience_years integer   NOT NULL DEFAULT 0,
  home_plant_id integer REFERENCES locations(id),
  safety_score  integer      NOT NULL DEFAULT 100,
  joined_on     date,
  archived_at   timestamptz,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_drivers_status ON drivers (status) WHERE archived_at IS NULL;
CREATE INDEX idx_drivers_name ON drivers (lower(full_name) text_pattern_ops);

CREATE TABLE vehicles (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(30)  NOT NULL UNIQUE,    -- fleet code e.g. GAS-BZ-001 (synthetic)
  registration_no varchar(30) NOT NULL UNIQUE,
  fleet_type    varchar(10)  NOT NULL CHECK (fleet_type IN ('OWNED','HIRED')),
  category      varchar(20)  NOT NULL DEFAULT 'BOWZER' CHECK (category IN ('BOWZER','CYLINDER_TRUCK')),
  capacity_mt   numeric(6,1) NOT NULL,
  make          varchar(40),
  model         varchar(40),
  year          integer,
  status        varchar(15)  NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','ON_TRIP','MAINTENANCE','INACTIVE')),
  home_plant_id integer REFERENCES locations(id),
  default_driver_id integer REFERENCES drivers(id),
  vendor_name   varchar(120),                     -- hired fleet only
  odometer_km   integer NOT NULL DEFAULT 0,
  last_lat      double precision,
  last_lng      double precision,
  last_speed_kmh integer,
  last_position_at timestamptz,
  last_location_id integer REFERENCES locations(id),
  archived_at   timestamptz,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_vehicles_status ON vehicles (status) WHERE archived_at IS NULL;
CREATE INDEX idx_vehicles_fleet ON vehicles (fleet_type) WHERE archived_at IS NULL;

CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         varchar(190) NOT NULL,
  password_hash varchar(100) NOT NULL,
  full_name     varchar(120) NOT NULL,
  role          varchar(30)  NOT NULL,
  phone         varchar(30),
  driver_id     integer REFERENCES drivers(id),
  status        varchar(15)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
  failed_logins integer      NOT NULL DEFAULT 0,
  locked_until  timestamptz,
  last_login_at timestamptz,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_users_email ON users (lower(email));
CREATE INDEX idx_users_role ON users (role);

CREATE TABLE refresh_tokens (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash    char(64) NOT NULL UNIQUE,
  family_id     varchar(40) NOT NULL,
  expires_at    timestamptz NOT NULL,
  revoked_at    timestamptz,
  user_agent    varchar(250),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_refresh_user ON refresh_tokens (user_id);

CREATE TABLE documents (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id    integer REFERENCES vehicles(id) ON DELETE CASCADE,
  driver_id     integer REFERENCES drivers(id) ON DELETE CASCADE,
  doc_type      varchar(30) NOT NULL,
  doc_number    varchar(60),
  issued_on     date,
  expires_on    date NOT NULL,
  issuer        varchar(120),
  notes         varchar(250),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CHECK ((vehicle_id IS NOT NULL)::int + (driver_id IS NOT NULL)::int = 1)
);
CREATE INDEX idx_docs_vehicle ON documents (vehicle_id, doc_type);
CREATE INDEX idx_docs_driver ON documents (driver_id, doc_type);
CREATE INDEX idx_docs_expiry ON documents (expires_on);

CREATE TABLE trips (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(30) NOT NULL UNIQUE,
  status        varchar(15) NOT NULL DEFAULT 'DRAFT',
  status_before_hold varchar(15),
  priority      varchar(10) NOT NULL DEFAULT 'NORMAL',
  origin_location_id      integer NOT NULL REFERENCES locations(id),
  destination_location_id integer NOT NULL REFERENCES locations(id),
  distributor_id integer REFERENCES distributors(id),
  route_id      integer REFERENCES routes(id),
  vehicle_id    integer REFERENCES vehicles(id),
  driver_id     integer REFERENCES drivers(id),
  lpg_source    varchar(10) NOT NULL DEFAULT 'LOCAL',
  planned_load_mt   numeric(6,2) NOT NULL,
  loaded_mt         numeric(6,2),
  delivered_mt      numeric(6,2),
  scheduled_departure timestamptz NOT NULL,
  planned_arrival     timestamptz NOT NULL,
  dispatched_at     timestamptz,
  departed_at       timestamptz,
  arrived_at        timestamptz,
  delivered_at      timestamptz,
  return_started_at timestamptz,
  completed_at      timestamptz,
  cancelled_at      timestamptz,
  delay_minutes     integer NOT NULL DEFAULT 0,
  hold_reason       varchar(250),
  cancel_reason     varchar(250),
  delivery_note_no  varchar(40),
  received_by       varchar(120),
  pod_notes         varchar(500),
  notes             varchar(500),
  -- live tracking snapshot (denormalised for cheap list/map reads)
  progress_pct      numeric(5,1) NOT NULL DEFAULT 0,
  cur_lat           double precision,
  cur_lng           double precision,
  cur_speed_kmh     integer,
  eta_at            timestamptz,
  last_position_at  timestamptz,
  created_by        integer REFERENCES users(id),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CHECK (planned_arrival > scheduled_departure)
);
CREATE INDEX idx_trips_status_dep ON trips (status, scheduled_departure DESC);
CREATE INDEX idx_trips_dep ON trips (scheduled_departure DESC);
CREATE INDEX idx_trips_vehicle ON trips (vehicle_id, scheduled_departure DESC);
CREATE INDEX idx_trips_driver ON trips (driver_id, scheduled_departure DESC);
CREATE INDEX idx_trips_origin ON trips (origin_location_id);
CREATE INDEX idx_trips_dest ON trips (destination_location_id);
CREATE INDEX idx_trips_completed ON trips (completed_at) WHERE status = 'COMPLETED';
-- Safety net against double-booking when two dispatchers act at once:
CREATE UNIQUE INDEX uq_trips_vehicle_active ON trips (vehicle_id)
  WHERE status IN ('DISPATCHED','IN_TRANSIT','DELAYED','ON_HOLD','ARRIVED','DELIVERED','RETURNING') AND vehicle_id IS NOT NULL;
CREATE UNIQUE INDEX uq_trips_driver_active ON trips (driver_id)
  WHERE status IN ('DISPATCHED','IN_TRANSIT','DELAYED','ON_HOLD','ARRIVED','DELIVERED','RETURNING') AND driver_id IS NOT NULL;

CREATE TABLE trip_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id       integer NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  type          varchar(20) NOT NULL,   -- STATUS_CHANGE | ASSIGNMENT | CHECKPOINT | NOTE | ALERT | CHECK
  from_status   varchar(15),
  to_status     varchar(15),
  message       varchar(400) NOT NULL,
  actor_user_id integer REFERENCES users(id),
  lat           double precision,
  lng           double precision,
  client_event_id varchar(60),          -- idempotency key from mobile clients
  occurred_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_trip_events_trip ON trip_events (trip_id, occurred_at DESC);
CREATE UNIQUE INDEX uq_trip_events_client ON trip_events (trip_id, client_event_id) WHERE client_event_id IS NOT NULL;

CREATE TABLE trip_positions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id       integer NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  lat           double precision NOT NULL,
  lng           double precision NOT NULL,
  speed_kmh     integer,
  heading       integer,
  recorded_at   timestamptz NOT NULL
);
CREATE INDEX idx_positions_trip ON trip_positions (trip_id, recorded_at DESC);

CREATE TABLE safety_checks (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id       integer REFERENCES trips(id) ON DELETE CASCADE,
  vehicle_id    integer NOT NULL REFERENCES vehicles(id),
  driver_id     integer REFERENCES drivers(id),
  kind          varchar(15) NOT NULL DEFAULT 'PRE_TRIP' CHECK (kind IN ('PRE_TRIP','POST_TRIP')),
  result        varchar(10) NOT NULL CHECK (result IN ('PASS','FAIL')),
  items         jsonb NOT NULL,                  -- [{key,label,ok,note}]
  notes         varchar(400),
  completed_by  integer REFERENCES users(id),
  completed_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_checks_trip ON safety_checks (trip_id);
CREATE INDEX idx_checks_vehicle ON safety_checks (vehicle_id, completed_at DESC);

CREATE TABLE incidents (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(30) NOT NULL UNIQUE,
  trip_id       integer REFERENCES trips(id),
  vehicle_id    integer REFERENCES vehicles(id),
  driver_id     integer REFERENCES drivers(id),
  category      varchar(20) NOT NULL,
  severity      varchar(10) NOT NULL,
  status        varchar(15) NOT NULL DEFAULT 'OPEN',
  description   varchar(1000) NOT NULL,
  resolution    varchar(1000),
  lat           double precision,
  lng           double precision,
  reported_by   integer REFERENCES users(id),
  reported_at   timestamptz NOT NULL DEFAULT now(),
  closed_at     timestamptz
);
CREATE INDEX idx_incidents_status ON incidents (status, reported_at DESC);
CREATE INDEX idx_incidents_vehicle ON incidents (vehicle_id);
CREATE INDEX idx_incidents_driver ON incidents (driver_id);

CREATE TABLE maintenance_records (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id    integer NOT NULL REFERENCES vehicles(id),
  type          varchar(15) NOT NULL,
  status        varchar(15) NOT NULL DEFAULT 'SCHEDULED',
  title         varchar(150) NOT NULL,
  description   varchar(500),
  scheduled_on  date NOT NULL,
  started_at    timestamptz,
  completed_at  timestamptz,
  odometer_km   integer,
  cost_pkr      numeric(12,0),
  vendor        varchar(120),
  created_by    integer REFERENCES users(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_maint_vehicle ON maintenance_records (vehicle_id, scheduled_on DESC);
CREATE INDEX idx_maint_status ON maintenance_records (status, scheduled_on);

CREATE TABLE notifications (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer REFERENCES users(id) ON DELETE CASCADE,  -- targeted, or NULL = broadcast to roles
  roles         varchar(30)[],                                    -- broadcast audience (NULL when user_id set)
  type          varchar(30) NOT NULL,
  severity      varchar(10) NOT NULL DEFAULT 'INFO' CHECK (severity IN ('INFO','WARNING','CRITICAL','SUCCESS')),
  title         varchar(160) NOT NULL,
  body          varchar(400),
  entity_type   varchar(20),
  entity_id     integer,
  dedupe_key    varchar(100),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_user ON notifications (user_id, id DESC);
CREATE INDEX idx_notif_created ON notifications (id DESC);
CREATE UNIQUE INDEX uq_notif_dedupe ON notifications (dedupe_key) WHERE dedupe_key IS NOT NULL;

CREATE TABLE notification_reads (
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_id bigint  NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  read_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, notification_id)
);

CREATE TABLE audit_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer,
  user_email    varchar(190),
  action        varchar(40) NOT NULL,
  entity_type   varchar(30),
  entity_id     integer,
  entity_label  varchar(120),
  ip            varchar(60),
  meta          jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_created ON audit_logs (id DESC);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id, id DESC);
CREATE INDEX idx_audit_user ON audit_logs (user_id, id DESC);
