-- Phase A: old-system parity (uplifting trips, freight per MT, odometer, trip expenses, fuel) + approvals + settings.

ALTER TABLE locations DROP CONSTRAINT IF EXISTS locations_type_check;
ALTER TABLE locations ADD CONSTRAINT locations_type_check CHECK (type IN ('PLANT','TERMINAL','DEPOT','DISTRIBUTOR','PARKING','FIELD'));

ALTER TABLE vehicles
  ADD COLUMN bowzer_no varchar(30), ADD COLUMN chassis_no varchar(40), ADD COLUMN engine_no varchar(40),
  ADD COLUMN wheels integer, ADD COLUMN owner_name varchar(120),
  ADD COLUMN fuel_norm_kmpl numeric(4,1) NOT NULL DEFAULT 2.6;
CREATE INDEX idx_vehicles_owner ON vehicles (owner_name) WHERE archived_at IS NULL;

-- distributors double as the customer master (receivables)
ALTER TABLE distributors
  ADD COLUMN customer_type varchar(15) NOT NULL DEFAULT 'DISTRIBUTOR' CHECK (customer_type IN ('DISTRIBUTOR','MARKETER','OTHER')),
  ADD COLUMN credit_limit_pkr numeric(14,0) NOT NULL DEFAULT 0,
  ADD COLUMN credit_alert_pct integer NOT NULL DEFAULT 80,
  ADD COLUMN whatsapp varchar(30), ADD COLUMN email varchar(120), ADD COLUMN ntn varchar(30);

ALTER TABLE routes ADD COLUMN freight_per_mt numeric(10,2) NOT NULL DEFAULT 0, ADD COLUMN active boolean NOT NULL DEFAULT true, ADD COLUMN name varchar(150);

ALTER TABLE trips
  ADD COLUMN trip_type varchar(12) NOT NULL DEFAULT 'DELIVERY' CHECK (trip_type IN ('DELIVERY','UPLIFTING')),
  ADD COLUMN freight_per_mt numeric(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN uplift_voucher_no varchar(40),
  ADD COLUMN odometer_start integer, ADD COLUMN odometer_end integer,
  ADD COLUMN public_token varchar(40),
  ADD COLUMN bill_to_id integer REFERENCES distributors(id),
  ADD COLUMN invoice_id integer;
CREATE UNIQUE INDEX uq_trips_public_token ON trips (public_token) WHERE public_token IS NOT NULL;
CREATE INDEX idx_trips_bill_to ON trips (bill_to_id) WHERE invoice_id IS NULL AND status = 'COMPLETED';

CREATE TABLE fuel_entries (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id    integer NOT NULL REFERENCES vehicles(id),
  trip_id       integer REFERENCES trips(id) ON DELETE SET NULL,
  driver_id     integer REFERENCES drivers(id),
  station       varchar(120),
  fueled_at     timestamptz NOT NULL DEFAULT now(),
  litres        numeric(8,2) NOT NULL CHECK (litres > 0),
  rate_per_l    numeric(8,2) NOT NULL CHECK (rate_per_l > 0),
  amount        numeric(12,0) NOT NULL,
  odometer_km   integer,
  km_since_last integer,
  kmpl          numeric(5,2),
  payment_mode  varchar(10) NOT NULL DEFAULT 'CASH' CHECK (payment_mode IN ('CASH','CARD','CREDIT')),
  receipt_no    varchar(40),
  status        varchar(10) NOT NULL DEFAULT 'VALIDATED' CHECK (status IN ('VALIDATED','FLAGGED','REVIEWED')),
  variance_pct  numeric(6,1),
  flag_reason   varchar(250),
  reviewed_by   integer REFERENCES users(id),
  review_note   varchar(250),
  created_by    integer REFERENCES users(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_fuel_vehicle ON fuel_entries (vehicle_id, fueled_at DESC);
CREATE INDEX idx_fuel_trip ON fuel_entries (trip_id);
CREATE INDEX idx_fuel_status ON fuel_entries (status, fueled_at DESC);

CREATE TABLE trip_expenses (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id       integer NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  vehicle_id    integer REFERENCES vehicles(id),
  driver_id     integer REFERENCES drivers(id),
  category      varchar(20) NOT NULL,
  amount        numeric(12,0) NOT NULL CHECK (amount > 0),
  nights        integer,
  description   varchar(250),
  receipt_no    varchar(40),
  incurred_on   date NOT NULL DEFAULT CURRENT_DATE,
  status        varchar(12) NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','APPROVED','REJECTED','REIMBURSED')),
  submitted_by  integer REFERENCES users(id),
  decided_by    integer REFERENCES users(id),
  decided_at    timestamptz,
  decision_note varchar(250),
  fuel_entry_id integer REFERENCES fuel_entries(id) ON DELETE SET NULL,
  voucher_id    integer,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_expenses_trip ON trip_expenses (trip_id);
CREATE INDEX idx_expenses_status ON trip_expenses (status, created_at DESC);
CREATE INDEX idx_expenses_vehicle ON trip_expenses (vehicle_id, incurred_on DESC);

CREATE TABLE settings (
  key         varchar(60) PRIMARY KEY,
  value       jsonb NOT NULL,
  label       varchar(120) NOT NULL,
  description varchar(300),
  group_name  varchar(40) NOT NULL DEFAULT 'General',
  updated_by  integer REFERENCES users(id),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE approval_rules (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type   varchar(30) NOT NULL,
  min_amount    numeric(14,0) NOT NULL DEFAULT 0,
  approver_role varchar(30) NOT NULL,
  active        boolean NOT NULL DEFAULT true,
  note          varchar(200)
);
CREATE INDEX idx_rules_entity ON approval_rules (entity_type, min_amount);

CREATE TABLE approvals (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type   varchar(30) NOT NULL,
  entity_id     integer NOT NULL,
  title         varchar(200) NOT NULL,
  amount        numeric(14,0),
  requested_by  integer REFERENCES users(id),
  requested_at  timestamptz NOT NULL DEFAULT now(),
  approver_role varchar(30) NOT NULL,
  status        varchar(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
  decided_by    integer REFERENCES users(id),
  decided_at    timestamptz,
  decision_note varchar(300)
);
CREATE INDEX idx_approvals_status ON approvals (status, approver_role, requested_at);
CREATE UNIQUE INDEX uq_approvals_pending ON approvals (entity_type, entity_id) WHERE status = 'PENDING';
