-- Phase B: Finance & Sales. Double-entry ledger with dimensions (bowzer/vehicle, party, trip), vouchers (no POS), invoices, vendors.

CREATE TABLE fiscal_years (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label     varchar(20) NOT NULL UNIQUE,          -- e.g. 2026-27
  starts_on date NOT NULL,
  ends_on   date NOT NULL CHECK (ends_on > starts_on),
  status    varchar(8) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED'))
);

CREATE TABLE accounts (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(20) NOT NULL UNIQUE,
  name       varchar(120) NOT NULL,
  type       varchar(10) NOT NULL CHECK (type IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
  parent_id  integer REFERENCES accounts(id),
  level      integer NOT NULL DEFAULT 1,
  postable   boolean NOT NULL DEFAULT true,       -- false = group/heading account
  system_key varchar(40) UNIQUE,                  -- stable handle used by auto-postings
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_accounts_parent ON accounts (parent_id);

CREATE TABLE banks (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(120) NOT NULL,
  branch     varchar(120),
  account_no varchar(40),
  account_id integer NOT NULL REFERENCES accounts(id),
  active     boolean NOT NULL DEFAULT true
);

CREATE TABLE vendors (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(20) NOT NULL UNIQUE,
  name       varchar(150) NOT NULL,
  category   varchar(20) NOT NULL DEFAULT 'SUPPLIER' CHECK (category IN ('SUPPLIER','TRANSPORTER','WORKSHOP','FUEL_STATION','REFINERY','SERVICE','OTHER')),
  contact_name varchar(120), phone varchar(30), email varchar(120), city varchar(80), address varchar(250), ntn varchar(30),
  payment_terms_days integer NOT NULL DEFAULT 0,
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE vouchers (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_no     varchar(30) NOT NULL UNIQUE,
  type           varchar(20) NOT NULL CHECK (type IN ('CASH_PAYMENT','CASH_RECEIPT','BANK_PAYMENT','BANK_RECEIVE','JOURNAL','BOWZER_EXPENSE','SALE_INVOICE','SALE_RETURN','PURCHASE','PURCHASE_RETURN','PAYROLL','TRIP_EXPENSE','TRIP_FREIGHT','STOCK','OPENING')),
  voucher_date   date NOT NULL,
  fiscal_year_id integer NOT NULL REFERENCES fiscal_years(id),
  narration      varchar(300),
  total          numeric(16,2) NOT NULL DEFAULT 0,
  vehicle_id     integer REFERENCES vehicles(id),
  party_type     varchar(12) CHECK (party_type IN ('CUSTOMER','VENDOR','EMPLOYEE','OWNER')),
  party_id       integer,
  trip_id        integer REFERENCES trips(id) ON DELETE SET NULL,
  source_type    varchar(20),
  source_id      integer,
  status         varchar(8) NOT NULL DEFAULT 'POSTED' CHECK (status IN ('POSTED','VOID')),
  void_reason    varchar(250),
  created_by     integer REFERENCES users(id),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_vouchers_date ON vouchers (voucher_date DESC, id DESC);
CREATE INDEX idx_vouchers_type ON vouchers (type, voucher_date DESC);
CREATE INDEX idx_vouchers_vehicle ON vouchers (vehicle_id) WHERE vehicle_id IS NOT NULL;
CREATE INDEX idx_vouchers_trip ON vouchers (trip_id) WHERE trip_id IS NOT NULL;
CREATE UNIQUE INDEX uq_vouchers_source ON vouchers (source_type, source_id) WHERE source_type IS NOT NULL AND status = 'POSTED';

CREATE TABLE voucher_lines (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id  integer NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,
  line_no     integer NOT NULL,
  account_id  integer NOT NULL REFERENCES accounts(id),
  debit       numeric(16,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit      numeric(16,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
  vehicle_id  integer REFERENCES vehicles(id),
  party_type  varchar(12) CHECK (party_type IN ('CUSTOMER','VENDOR','EMPLOYEE','OWNER')),
  party_id    integer,
  trip_id     integer REFERENCES trips(id) ON DELETE SET NULL,
  memo        varchar(250),
  CHECK (NOT (debit > 0 AND credit > 0)),
  CHECK (debit > 0 OR credit > 0)
);
CREATE INDEX idx_vl_voucher ON voucher_lines (voucher_id);
CREATE INDEX idx_vl_account ON voucher_lines (account_id, voucher_id);
CREATE INDEX idx_vl_vehicle ON voucher_lines (vehicle_id, account_id) WHERE vehicle_id IS NOT NULL;
CREATE INDEX idx_vl_party ON voucher_lines (party_type, party_id) WHERE party_id IS NOT NULL;
CREATE INDEX idx_vl_trip ON voucher_lines (trip_id) WHERE trip_id IS NOT NULL;

-- Integrity: every voucher must balance at commit time, whatever code path wrote it.
CREATE FUNCTION check_voucher_balance() RETURNS trigger AS $$
DECLARE d numeric; c numeric;
BEGIN
  SELECT COALESCE(sum(debit),0), COALESCE(sum(credit),0) INTO d, c FROM voucher_lines WHERE voucher_id = NEW.voucher_id;
  IF d <> c THEN RAISE EXCEPTION 'Voucher % is unbalanced (debit % / credit %)', NEW.voucher_id, d, c; END IF;
  RETURN NULL;
END $$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER trg_voucher_balance AFTER INSERT OR UPDATE ON voucher_lines
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_voucher_balance();

CREATE TABLE voucher_counters (
  prefix varchar(8) NOT NULL, fiscal_year_id integer NOT NULL REFERENCES fiscal_years(id), last_no integer NOT NULL DEFAULT 0,
  PRIMARY KEY (prefix, fiscal_year_id)
);

-- Sales (no POS): orders and invoices billed to customers (distributors / marketers); each bowzer is also a cost/profit account via the vehicle dimension.
CREATE TABLE sales_orders (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no    varchar(30) NOT NULL UNIQUE,
  order_date  date NOT NULL,
  customer_id integer NOT NULL REFERENCES distributors(id),
  delivery_date date,
  status      varchar(10) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','INVOICED','CANCELLED')),
  notes       varchar(300),
  total       numeric(14,2) NOT NULL DEFAULT 0,
  created_by  integer REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_so_customer ON sales_orders (customer_id, order_date DESC);

CREATE TABLE sales_invoices (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no  varchar(30) NOT NULL UNIQUE,
  kind        varchar(8) NOT NULL DEFAULT 'INVOICE' CHECK (kind IN ('INVOICE','RETURN')),
  invoice_date date NOT NULL,
  due_date    date NOT NULL,
  customer_id integer NOT NULL REFERENCES distributors(id),
  trip_id     integer REFERENCES trips(id) ON DELETE SET NULL,
  order_id    integer REFERENCES sales_orders(id) ON DELETE SET NULL,
  ref_invoice_id integer REFERENCES sales_invoices(id),
  subtotal    numeric(14,2) NOT NULL,
  tax_pct     numeric(5,2) NOT NULL DEFAULT 0,
  tax_amount  numeric(14,2) NOT NULL DEFAULT 0,
  total       numeric(14,2) NOT NULL,
  paid        numeric(14,2) NOT NULL DEFAULT 0,
  status      varchar(8) NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID','PARTIAL','PAID','VOID')),
  voucher_id  integer REFERENCES vouchers(id),
  notes       varchar(300),
  created_by  integer REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_si_customer ON sales_invoices (customer_id, invoice_date DESC);
CREATE INDEX idx_si_status ON sales_invoices (status, due_date) WHERE status IN ('UNPAID','PARTIAL');
CREATE UNIQUE INDEX uq_si_trip ON sales_invoices (trip_id) WHERE trip_id IS NOT NULL AND kind = 'INVOICE' AND status <> 'VOID';

CREATE TABLE sales_invoice_lines (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id  integer NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  line_no     integer NOT NULL,
  description varchar(250) NOT NULL,
  qty         numeric(12,3) NOT NULL CHECK (qty > 0),
  unit        varchar(10) NOT NULL DEFAULT 'MT',
  rate        numeric(12,2) NOT NULL CHECK (rate >= 0),
  amount      numeric(14,2) NOT NULL,
  vehicle_id  integer REFERENCES vehicles(id)
);
CREATE INDEX idx_sil_invoice ON sales_invoice_lines (invoice_id);

CREATE TABLE sales_order_lines (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    integer NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  line_no     integer NOT NULL,
  description varchar(250) NOT NULL,
  qty         numeric(12,3) NOT NULL CHECK (qty > 0),
  unit        varchar(10) NOT NULL DEFAULT 'MT',
  rate        numeric(12,2) NOT NULL CHECK (rate >= 0),
  amount      numeric(14,2) NOT NULL
);

-- Receipts allocate to invoices (settles receivables).
CREATE TABLE voucher_allocations (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id integer NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,
  invoice_id integer NOT NULL REFERENCES sales_invoices(id),
  amount     numeric(14,2) NOT NULL CHECK (amount > 0)
);
CREATE INDEX idx_va_invoice ON voucher_allocations (invoice_id);
CREATE INDEX idx_va_voucher ON voucher_allocations (voucher_id);

ALTER TABLE trips ADD CONSTRAINT fk_trips_invoice FOREIGN KEY (invoice_id) REFERENCES sales_invoices(id);
ALTER TABLE trip_expenses ADD CONSTRAINT fk_exp_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id);
ALTER TABLE distributors ADD COLUMN opening_balance numeric(14,2) NOT NULL DEFAULT 0;

CREATE SEQUENCE invoice_no_seq START 1;
CREATE SEQUENCE sales_order_no_seq START 1;

-- Chart of accounts (levelled). System accounts are referenced by key from auto-postings.
INSERT INTO accounts (code, name, type, parent_id, level, postable, system_key) VALUES
 ('1000','Assets','ASSET',NULL,1,false,NULL),
 ('2000','Liabilities','LIABILITY',NULL,1,false,NULL),
 ('3000','Equity','EQUITY',NULL,1,false,NULL),
 ('4000','Income','INCOME',NULL,1,false,NULL),
 ('5000','Expenses','EXPENSE',NULL,1,false,NULL);
INSERT INTO accounts (code, name, type, parent_id, level, postable, system_key)
SELECT v.code, v.name, v.type, p.id, 2, v.postable, v.k FROM (VALUES
 ('1100','Current assets','ASSET','1000',false,NULL),
 ('1200','Fixed assets','ASSET','1000',false,NULL),
 ('2100','Current liabilities','LIABILITY','2000',false,NULL),
 ('3100','Owner capital','EQUITY','3000',true,'capital'),
 ('3200','Retained earnings','EQUITY','3000',true,'retained'),
 ('4100','Freight income','INCOME','4000',false,NULL),
 ('4900','Other income','INCOME','4000',true,'other_income'),
 ('5100','Trip expenses','EXPENSE','5000',false,NULL),
 ('5200','Workshop & parts','EXPENSE','5000',false,NULL),
 ('5300','Payroll','EXPENSE','5000',false,NULL),
 ('5400','Administration','EXPENSE','5000',false,NULL)
) AS v(code,name,type,pcode,postable,k) JOIN accounts p ON p.code = v.pcode;
INSERT INTO accounts (code, name, type, parent_id, level, postable, system_key)
SELECT v.code, v.name, v.type, p.id, 3, true, v.k FROM (VALUES
 ('1110','Cash in hand','ASSET','1100','cash'),
 ('1120','Bank accounts','ASSET','1100','bank_control'),
 ('1130','Accounts receivable','ASSET','1100','receivable'),
 ('1140','Staff & driver advances','ASSET','1100','advances'),
 ('1150','Inventory — spares, tyres, accessories','ASSET','1100','inventory'),
 ('1210','Bowzers & vehicles (at cost)','ASSET','1200','vehicles_asset'),
 ('2110','Accounts payable — vendors','LIABILITY','2100','payable'),
 ('2120','Salaries payable','LIABILITY','2100','salaries_payable'),
 ('2130','Sales tax payable','LIABILITY','2100','tax_payable'),
 ('4110','Freight income — delivery','INCOME','4100','freight_delivery'),
 ('4120','Freight income — uplifting','INCOME','4100','freight_uplift'),
 ('4130','Sales returns & allowances','INCOME','4100','sales_returns'),
 ('5110','Fuel','EXPENSE','5100','exp_FUEL'),
 ('5120','Toll & road tax','EXPENSE','5100','exp_TOLL'),
 ('5130','Driver allowance','EXPENSE','5100','exp_DRIVER_ALLOWANCE'),
 ('5140','Tour stay (halts)','EXPENSE','5100','exp_TOUR_STAY'),
 ('5150','Loading / unloading','EXPENSE','5100','exp_LOADING_UNLOADING'),
 ('5160','En-route repairs','EXPENSE','5100','exp_REPAIR'),
 ('5170','Road / police charges','EXPENSE','5100','exp_POLICE_ROAD'),
 ('5180','Other trip expenses','EXPENSE','5100','exp_OTHER'),
 ('5210','Repairs & maintenance','EXPENSE','5200','exp_maintenance'),
 ('5220','Tyres','EXPENSE','5200','exp_tyres'),
 ('5230','Spare parts & accessories','EXPENSE','5200','exp_parts'),
 ('5310','Salaries & wages','EXPENSE','5300','exp_salaries'),
 ('5320','Driver trip bonus','EXPENSE','5300','exp_bonus'),
 ('5410','Office & utilities','EXPENSE','5400','exp_office'),
 ('5420','Insurance & registration','EXPENSE','5400','exp_insurance'),
 ('5430','Bank charges','EXPENSE','5400','exp_bank')
) AS v(code,name,type,pcode,k) JOIN accounts p ON p.code = v.pcode;

INSERT INTO fiscal_years (label, starts_on, ends_on, status) VALUES ('2025-26','2025-07-01','2026-06-30','CLOSED'), ('2026-27','2026-07-01','2027-06-30','OPEN');

-- Bank accounts are created per bank under this heading.
UPDATE accounts SET postable = false WHERE system_key = 'bank_control';
