-- Phase C: Inventory (vehicle-centred), stock vouchers, procurement, tyres.
-- Stock can sit in a WAREHOUSE or be fitted to a VEHICLE (bowzer): "5 cameras in vehicle A, 3 in vehicle B".

CREATE TABLE item_categories (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(80) NOT NULL UNIQUE,
  kind varchar(12) NOT NULL DEFAULT 'SPARE' CHECK (kind IN ('SPARE','TYRE','CAMERA','ACCESSORY','LUBRICANT','SAFETY','TOOL','OTHER'))
);
CREATE TABLE item_subcategories (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL REFERENCES item_categories(id),
  name        varchar(80) NOT NULL,
  UNIQUE (category_id, name)
);
CREATE TABLE brands (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(80) NOT NULL UNIQUE);

CREATE TABLE items (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           varchar(30) NOT NULL UNIQUE,
  name           varchar(150) NOT NULL,
  category_id    integer NOT NULL REFERENCES item_categories(id),
  subcategory_id integer REFERENCES item_subcategories(id),
  brand_id       integer REFERENCES brands(id),
  made_in        varchar(60),
  unit           varchar(10) NOT NULL DEFAULT 'PCS',
  min_level      numeric(12,3) NOT NULL DEFAULT 0,
  reorder_qty    numeric(12,3) NOT NULL DEFAULT 0,
  avg_cost       numeric(14,2) NOT NULL DEFAULT 0,        -- moving average, PKR
  serialized     boolean NOT NULL DEFAULT false,
  active         boolean NOT NULL DEFAULT true,
  notes          varchar(300),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_items_cat ON items (category_id) WHERE active;

CREATE TABLE warehouses (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        varchar(20) NOT NULL UNIQUE,
  name        varchar(120) NOT NULL,
  location_id integer REFERENCES locations(id),
  active      boolean NOT NULL DEFAULT true
);

CREATE TABLE stock_docs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_no      varchar(30) NOT NULL UNIQUE,
  type        varchar(20) NOT NULL CHECK (type IN ('OPENING','PURCHASE','PURCHASE_RETURN','NAVIGATION','PARTS_REPLACEMENT','ISSUE','ADJUSTMENT')),
  doc_date    date NOT NULL,
  from_type   varchar(10) CHECK (from_type IN ('WAREHOUSE','VEHICLE')),
  from_id     integer,
  to_type     varchar(10) CHECK (to_type IN ('WAREHOUSE','VEHICLE')),
  to_id       integer,
  vehicle_id  integer REFERENCES vehicles(id),
  vendor_id   integer REFERENCES vendors(id),
  po_id       integer,
  pay_mode    varchar(10),
  narration   varchar(300),
  total_value numeric(16,2) NOT NULL DEFAULT 0,
  status      varchar(8) NOT NULL DEFAULT 'POSTED' CHECK (status IN ('POSTED','VOID')),
  voucher_id  integer REFERENCES vouchers(id),
  created_by  integer REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sd_date ON stock_docs (doc_date DESC, id DESC);
CREATE INDEX idx_sd_vehicle ON stock_docs (vehicle_id) WHERE vehicle_id IS NOT NULL;
CREATE INDEX idx_sd_type ON stock_docs (type, doc_date DESC);

CREATE TABLE stock_doc_lines (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id              integer NOT NULL REFERENCES stock_docs(id) ON DELETE CASCADE,
  line_no             integer NOT NULL,
  item_id             integer NOT NULL REFERENCES items(id),
  qty                 numeric(12,3) NOT NULL,
  unit_cost           numeric(14,2) NOT NULL DEFAULT 0,
  line_value          numeric(16,2) NOT NULL DEFAULT 0,
  serial_no           varchar(60),
  position            varchar(12),
  remove_item_id      integer REFERENCES items(id),
  remove_qty          numeric(12,3),
  remove_serial_no    varchar(60),
  remove_disposition  varchar(12) CHECK (remove_disposition IN ('SCRAP','RETURN','RETREAD')),
  reason              varchar(250)
);
CREATE INDEX idx_sdl_doc ON stock_doc_lines (doc_id);
CREATE INDEX idx_sdl_item ON stock_doc_lines (item_id);

CREATE TABLE stock_movements (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id        integer NOT NULL REFERENCES stock_docs(id) ON DELETE CASCADE,
  item_id       integer NOT NULL REFERENCES items(id),
  movement_date date NOT NULL,
  holder_type   varchar(10) NOT NULL CHECK (holder_type IN ('WAREHOUSE','VEHICLE','VENDOR','SCRAP','CONSUMED')),
  holder_id     integer NOT NULL DEFAULT 0,
  qty           numeric(12,3) NOT NULL,                   -- signed: + into the holder, - out of it
  unit_cost     numeric(14,2) NOT NULL DEFAULT 0,
  vehicle_id    integer REFERENCES vehicles(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sm_item ON stock_movements (item_id, movement_date, id);
CREATE INDEX idx_sm_holder ON stock_movements (holder_type, holder_id, item_id);
CREATE INDEX idx_sm_vehicle ON stock_movements (vehicle_id) WHERE vehicle_id IS NOT NULL;

-- Current quantity per holder. The CHECK makes negative stock impossible even if application code is bypassed.
CREATE TABLE stock_balances (
  item_id     integer NOT NULL REFERENCES items(id),
  holder_type varchar(10) NOT NULL CHECK (holder_type IN ('WAREHOUSE','VEHICLE')),
  holder_id   integer NOT NULL,
  qty         numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty >= 0),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (item_id, holder_type, holder_id)
);
CREATE INDEX idx_sb_holder ON stock_balances (holder_type, holder_id);

-- Procurement: requisition -> quotations (comparison) -> purchase order -> receipt (stock purchase doc)
CREATE TABLE purchase_requests (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_no        varchar(30) NOT NULL UNIQUE,
  pr_date      date NOT NULL,
  needed_by    date,
  vehicle_id   integer REFERENCES vehicles(id),
  requested_by integer REFERENCES users(id),
  status       varchar(12) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','ORDERED','CANCELLED')),
  est_value    numeric(14,2) NOT NULL DEFAULT 0,
  notes        varchar(300),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE purchase_request_lines (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id   integer NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
  line_no integer NOT NULL,
  item_id integer NOT NULL REFERENCES items(id),
  qty     numeric(12,3) NOT NULL CHECK (qty > 0),
  note    varchar(200)
);
CREATE TABLE rfq_quotes (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id       integer NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
  vendor_id   integer NOT NULL REFERENCES vendors(id),
  quoted_on   date NOT NULL,
  valid_until date,
  delivery_days integer,
  total       numeric(14,2) NOT NULL DEFAULT 0,
  selected    boolean NOT NULL DEFAULT false,
  UNIQUE (pr_id, vendor_id)
);
CREATE TABLE rfq_quote_lines (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id   integer NOT NULL REFERENCES rfq_quotes(id) ON DELETE CASCADE,
  pr_line_id integer NOT NULL REFERENCES purchase_request_lines(id) ON DELETE CASCADE,
  rate       numeric(14,2) NOT NULL CHECK (rate >= 0)
);
CREATE TABLE purchase_orders (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_no      varchar(30) NOT NULL UNIQUE,
  po_date    date NOT NULL,
  vendor_id  integer NOT NULL REFERENCES vendors(id),
  pr_id      integer REFERENCES purchase_requests(id),
  expected_on date,
  status     varchar(10) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','PARTIAL','RECEIVED','CANCELLED')),
  total      numeric(14,2) NOT NULL DEFAULT 0,
  notes      varchar(300),
  created_by integer REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_po_vendor ON purchase_orders (vendor_id, po_date DESC);
CREATE TABLE purchase_order_lines (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id        integer NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  line_no      integer NOT NULL,
  item_id      integer NOT NULL REFERENCES items(id),
  qty          numeric(12,3) NOT NULL CHECK (qty > 0),
  rate         numeric(14,2) NOT NULL CHECK (rate >= 0),
  received_qty numeric(12,3) NOT NULL DEFAULT 0 CHECK (received_qty >= 0)
);
ALTER TABLE stock_docs ADD CONSTRAINT fk_sd_po FOREIGN KEY (po_id) REFERENCES purchase_orders(id);

-- Tyres: serial-tracked register with fitment history per bowzer.
CREATE TABLE tyres (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no    varchar(60) NOT NULL UNIQUE,
  item_id      integer NOT NULL REFERENCES items(id),
  size         varchar(30),
  cost         numeric(12,2) NOT NULL DEFAULT 0,
  status       varchar(10) NOT NULL DEFAULT 'IN_STORE' CHECK (status IN ('IN_STORE','FITTED','RETREAD','SCRAPPED')),
  warehouse_id integer REFERENCES warehouses(id),
  vehicle_id   integer REFERENCES vehicles(id),
  position     varchar(12),
  fitted_on    date,
  odometer_fit integer,
  km_run       integer NOT NULL DEFAULT 0,
  retread_count integer NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'FITTED') = (vehicle_id IS NOT NULL))
);
CREATE INDEX idx_tyres_vehicle ON tyres (vehicle_id) WHERE vehicle_id IS NOT NULL;
CREATE UNIQUE INDEX uq_tyre_position ON tyres (vehicle_id, position) WHERE status = 'FITTED';
CREATE TABLE tyre_events (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tyre_id    integer NOT NULL REFERENCES tyres(id) ON DELETE CASCADE,
  vehicle_id integer REFERENCES vehicles(id),
  event_type varchar(10) NOT NULL CHECK (event_type IN ('PURCHASED','FIT','REMOVE','ROTATE','RETREAD','SCRAP')),
  event_date date NOT NULL,
  odometer   integer,
  position   varchar(12),
  doc_id     integer REFERENCES stock_docs(id),
  note       varchar(250),
  created_by integer REFERENCES users(id)
);
CREATE INDEX idx_te_tyre ON tyre_events (tyre_id, event_date);
CREATE INDEX idx_te_vehicle ON tyre_events (vehicle_id, event_date DESC);

CREATE SEQUENCE stock_doc_seq START 1;
CREATE SEQUENCE pr_no_seq START 1;
CREATE SEQUENCE po_no_seq START 1;
