-- Phase D: HR & payroll, trip expense definitions, exception acknowledgements.

CREATE TABLE departments (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(80) NOT NULL UNIQUE);

CREATE TABLE employees (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(20) NOT NULL UNIQUE,
  full_name     varchar(120) NOT NULL,
  department_id integer REFERENCES departments(id),
  designation   varchar(80),
  employee_type varchar(10) NOT NULL DEFAULT 'STAFF' CHECK (employee_type IN ('STAFF','DRIVER','HELPER','MANAGER')),
  driver_id     integer UNIQUE REFERENCES drivers(id),
  phone         varchar(30),
  joined_on     date NOT NULL,
  status        varchar(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','LEFT')),
  basic_salary  numeric(12,2) NOT NULL DEFAULT 0 CHECK (basic_salary >= 0),
  allowances    numeric(12,2) NOT NULL DEFAULT 0 CHECK (allowances >= 0),
  trip_rate     numeric(10,2) NOT NULL DEFAULT 0 CHECK (trip_rate >= 0),
  bank_name     varchar(80),
  bank_account  varchar(40),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_emp_dept ON employees (department_id) WHERE status = 'ACTIVE';

CREATE TABLE attendance (
  employee_id integer NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  work_date   date NOT NULL,
  status      varchar(4) NOT NULL CHECK (status IN ('P','A','L','H','OFF')),   -- present, absent, leave, half day, weekly off
  check_in    time,
  check_out   time,
  note        varchar(200),
  PRIMARY KEY (employee_id, work_date)
);
CREATE INDEX idx_att_date ON attendance (work_date);

CREATE TABLE leave_requests (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   integer NOT NULL REFERENCES employees(id),
  leave_type    varchar(10) NOT NULL CHECK (leave_type IN ('ANNUAL','SICK','CASUAL','UNPAID')),
  from_date     date NOT NULL,
  to_date       date NOT NULL,
  days          numeric(4,1) NOT NULL CHECK (days > 0),
  reason        varchar(250),
  status        varchar(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
  requested_by  integer REFERENCES users(id),
  decided_by    integer REFERENCES users(id),
  decided_at    timestamptz,
  decision_note varchar(250),
  created_at    timestamptz NOT NULL DEFAULT now(),
  CHECK (to_date >= from_date)
);
CREATE INDEX idx_leave_emp ON leave_requests (employee_id, from_date DESC);
CREATE INDEX idx_leave_status ON leave_requests (status, created_at DESC);

CREATE TABLE payroll_runs (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period          char(7) NOT NULL UNIQUE,                 -- YYYY-MM
  status          varchar(10) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PENDING','APPROVED','POSTED','PAID','CANCELLED')),
  gross           numeric(14,2) NOT NULL DEFAULT 0,
  deductions      numeric(14,2) NOT NULL DEFAULT 0,
  net             numeric(14,2) NOT NULL DEFAULT 0,
  voucher_id      integer REFERENCES vouchers(id),
  paid_voucher_id integer REFERENCES vouchers(id),
  created_by      integer REFERENCES users(id),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE payroll_lines (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id            integer NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  employee_id       integer NOT NULL REFERENCES employees(id),
  basic             numeric(12,2) NOT NULL,
  allowances        numeric(12,2) NOT NULL DEFAULT 0,
  trips             integer NOT NULL DEFAULT 0,
  trip_bonus        numeric(12,2) NOT NULL DEFAULT 0,
  absent_days       numeric(4,1) NOT NULL DEFAULT 0,
  absence_deduction numeric(12,2) NOT NULL DEFAULT 0,
  other_deduction   numeric(12,2) NOT NULL DEFAULT 0,
  net               numeric(12,2) NOT NULL,
  UNIQUE (run_id, employee_id)
);

-- Trip expense definitions (old system: "Trip Expense Definition"): defaults and rules for each expense category.
CREATE TABLE expense_definitions (
  category         varchar(20) PRIMARY KEY,
  label            varchar(60) NOT NULL,
  default_amount   numeric(12,0) NOT NULL DEFAULT 0,
  requires_receipt boolean NOT NULL DEFAULT false,
  active           boolean NOT NULL DEFAULT true,
  note             varchar(200)
);
INSERT INTO expense_definitions (category, label, default_amount, requires_receipt, note) VALUES
  ('FUEL', 'Fuel', 0, true, 'Validated against the bowzer fuel norm'),
  ('TOLL', 'Toll / road tax', 1500, true, NULL),
  ('DRIVER_ALLOWANCE', 'Driver allowance', 2500, false, 'Per trip'),
  ('TOUR_STAY', 'Tour stay (halt)', 3000, false, 'Per night away from base'),
  ('LOADING_UNLOADING', 'Loading / unloading', 2000, false, NULL),
  ('REPAIR', 'En-route repair', 0, true, NULL),
  ('POLICE_ROAD', 'Road / police charges', 1000, false, NULL),
  ('OTHER', 'Other', 0, false, NULL);

-- Exceptions Center: acknowledgements keep a noisy rule quiet once someone has looked at it.
CREATE TABLE exception_acks (
  key        varchar(120) PRIMARY KEY,
  note       varchar(250),
  acked_by   integer REFERENCES users(id),
  acked_at   timestamptz NOT NULL DEFAULT now()
);
