-- Multi-drop trips: one trip (A -> B, C, D) with ordered delivery stops, each with its own load, ETA, POD and billing.
-- trips.destination_location_id / distributor_id keep pointing at the FINAL stop so every existing report keeps working;
-- trips.delivered_mt is the sum over stops and trips.freight_per_mt the quantity-weighted average rate.
CREATE TABLE trip_stops (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id          integer NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  seq              integer NOT NULL CHECK (seq >= 1),
  location_id      integer NOT NULL REFERENCES locations(id),
  distributor_id   integer REFERENCES distributors(id),
  planned_mt       numeric(6,2) NOT NULL CHECK (planned_mt > 0),
  delivered_mt     numeric(6,2),
  status           varchar(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ARRIVED','DELIVERED','SKIPPED')),
  route_frac       numeric(6,5) NOT NULL DEFAULT 1,
  eta_at           timestamptz,
  arrived_at       timestamptz,
  delivered_at     timestamptz,
  received_by      varchar(120),
  delivery_note_no varchar(40),
  pod_notes        varchar(500),
  skip_reason      varchar(250),
  freight_per_mt   numeric(10,2) NOT NULL DEFAULT 0,
  bill_to_id       integer REFERENCES distributors(id),
  UNIQUE (trip_id, seq)
);
CREATE INDEX idx_trip_stops_location ON trip_stops (location_id);
CREATE INDEX idx_trip_stops_dist ON trip_stops (distributor_id) WHERE distributor_id IS NOT NULL;

ALTER TABLE trips ADD COLUMN stop_count integer NOT NULL DEFAULT 1;

-- Multi-stop routes are composite and cannot satisfy the one-route-per-origin/destination rule.
ALTER TABLE routes ADD COLUMN kind varchar(8) NOT NULL DEFAULT 'DIRECT' CHECK (kind IN ('DIRECT','MULTI'));
ALTER TABLE routes DROP CONSTRAINT routes_origin_location_id_destination_location_id_key;
CREATE UNIQUE INDEX uq_routes_direct ON routes (origin_location_id, destination_location_id) WHERE kind = 'DIRECT';

-- One invoice per (trip, customer) so each distributor on a multi-drop trip is billed separately.
DROP INDEX uq_si_trip;
CREATE UNIQUE INDEX uq_si_trip ON sales_invoices (trip_id, customer_id) WHERE trip_id IS NOT NULL AND kind = 'INVOICE' AND status <> 'VOID';

INSERT INTO trip_stops (trip_id, seq, location_id, distributor_id, planned_mt, delivered_mt, status, route_frac, eta_at, arrived_at, delivered_at, received_by, delivery_note_no, pod_notes, freight_per_mt, bill_to_id)
SELECT t.id, 1, t.destination_location_id, t.distributor_id, t.planned_load_mt, t.delivered_mt,
       CASE WHEN t.status IN ('DELIVERED','RETURNING','COMPLETED') THEN 'DELIVERED' WHEN t.status = 'ARRIVED' THEN 'ARRIVED' ELSE 'PENDING' END,
       1, t.planned_arrival, t.arrived_at, t.delivered_at, t.received_by, t.delivery_note_no, t.pod_notes, COALESCE(t.freight_per_mt, 0), COALESCE(t.bill_to_id, t.distributor_id)
FROM trips t;
